const data = {
  products: [
    {
      id: 1,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "./images/img.jpg",
      price: 120,
      brand: "Nike",
      rating: 1,
      numReviewes: 12,
      description: "High quality product",
    },
    {
      id: 2,
      name: " Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 10,
      brand: "Nike",
      rating: 3,
      numReviewes: 7,
      description: "High quality product",
    },
    {
      id: 4,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviewes: 10,
      description: "High quality product",
    },
    {
      id: 4,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 12,
      brand: "Nike",
      rating: 4,
      numReviewes: 10,
      description: "High quality product",
    },
    {
      id: 5,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      numReviewes: 10,
      description: "High quality product",
    },
    {
      id: 6,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 1200,
      brand: "Nike",
      rating: 5,
      numReviewes: 0,
      description: "High quality product",
    },
    {
      id: 7,
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.jpg",
      price: 1200,
      brand: "Nike",
      rating: 1.5,
      numReviewes: 1,
      description: "High quality product",
    },
  ],
};
export default data;
